### ISSUE TITLE
Store Muzzle Information in DB

### ISSUE THREAD

**Issue by sfreeman422** [dev-chat/mocker#17]
**Describe the solution you'd like**
We should be storing the following information in a database for analysis later:
- Muzzle Requestor
- Muzzled Person
- Muzzle Length in milliseconds
- Date of Muzzle in UTC
- Messages Suppressed per Muzzle
- Characters Suppressed per Muzzle
- Words Suppressed per Muzzle

**Additional context**
This will add support for generating reports/analytics on muzzles. Once we have roughly one week of logging, we will add in support for generating reports.

**Comment by arrozconfrijoles** [comment]
**Additional Report**

Boolean of whether the muzzle had at least one successfully suppressed message. That would lead to a counter for each individual user. Slightly different from the messages suppressed per muzzle. Will factor into the KDR = (supressed boolean count)/(total muzzles)

**Example**
X muzzles Y who sends 100 messages - count = 1
X muzzles Z while Z is not using Slack, 0 messages suppressed - count unchanged
X's KDR = 1/2 - 50%

**Comment by sfreeman422** [comment]
The boolean you are describing can be derived from messagesSuppressed right? As long as that value is a non-zero amount, we can be certain that there was at least one suppressed message. 

**Example with Notes**
X muzzles Y who sends 100 messages - count = 1 - `this will create one muzzle entry, with messagesSuppressed, wordsSuppressed, charactersSuppressed added to the entry. We would have one muzzle, we a nonzero amount of messagesSuppressed. This would count as a K`
X muzzles Z while Z is handing out a pointless ticket, 0 messages suppressed - count unchanged - `this will also be one muzzle entry with 0 amounts for messagesSuppressed, wordsSuppressed and charactersSuppressed. This would not count as a K because of the 0 amount on messagesSuppressed`
X KDR = 1/2 - 50% - `when we later go to generate a KDR report. We can simply check whether the messagesSuppressed key has a non-zero amount, and if it does, we can count that as K`

Does that make sense? I dont think think it makes sense to add an additional boolean for storage on the data layer when this can later be derived on the server.

**Comment by sfreeman422** [comment]
The metrics we discussed above are now being stored in the DB. Once we have a week's worth of data, I will add some methods to report on the data.

**Comment by arrozconfrijoles** [comment]
The current KDR needs to be renamed to Accuracy.

The new KDR needs to be a measure of muzzler/muzzed

**New Feature**
A measure of either Stealth or Avoidance
avoidance = 1 - (message non-suppressed [aka avoided]/muzzled)

This one needs work on the naming and documentation. I originally thought it could equal 1 - accuracy but that would just give how inaccurate that particular user is.
