### ISSUE TITLE
Report Generation for Muzzles

### ISSUE THREAD

**Issue by sfreeman422** [dev-chat/mocker#23]
**Describe the solution you'd like**
Users should be able to generate reports on-demand via the `/muzzlestats` slash command.
Options for the command should be discussed in #muzzlefeedback and added here.

**Comment by comountainclimber** [comment]
👌

**Comment by arrozconfrijoles** [comment]
Do we want the command to start with "/muzzlePullRequest" or "/statsPullRequest"? The latter would allow us to maintain the ability to tab quickly while attempting a muzzle.

**Data Length**
The second idea that we'll need to address is the time span on our pulls. We could have a default setting of 7 days. A second layer of development could be to build out a day input. 
**Example**
/statsKDR  - defaults to a previous 7 day pull
/statsKDR 10  - pulls the last 10 days of data

- Top Muzzler (5 users) username + count
- Top Muzzled (5) username + count
- Longest Muzzled Time - single muzzle where user @channel (3) username + time 
- Longest Muzzle Word & Character Count (3) username + word count + character count
- Most Muzzled Messages (5) username (person J #1) + suppressed message count 
- KDR (all?) username + % KDR

_Probably Good Idea_
There should also be a way to unfurl all the stats for that particular /statsPullRequest. Maybe some sort of master stats pull with all the data mildly formatted and dumped?

_Maybe Unnecessary_
There could be room for abuse so we should probably cap /statsPulls to 2 per hour. Could be spammed but alternatively we could muzzle the /stats-puller to suppress them

**Comment by sfreeman422** [comment]
1. It shouldn't be called `/muzzlePullRequest` or `/statsPullRequest`. I was thinking something like `/stats` or to be more specific `/muzzlestats`.
2. Commands should accept parameters. I like what you had with passing in numeric days, and we should also allow for an `all` parameter that gives you all time data. Assuming a pattern of `/muzzlestats reportType reportSubtype timePeriod` Lets start with the below parameters, each parameter is required for a successful `/muzzlestats` call:

- reportType:
  - muzzled
  - muzzlers

- reportSubtype:
  - top5
  - top10
  - longest
  - words
  - chars
  - messages
  - kdr

Time period:
  - Any range of numbers 1-99999999 (maximum will stop at maximum available amount of data in db by date)
  - date range passed in EXPLICITLY as mm/dd/yyyy - mm/dd/yyyy
  - all

I think we can run with this a little bit and start thinking up some solutions. 

3. Re: "probably good idea" are you saying to just dump the entire contents of the DB? Almost like a kill feed showing all of the muzzle that happened, and who muzzled who?

4. We absolutely should limit this. The 2 per hour base is a good starting point.

**Comment by sfreeman422** [comment]
A version of this exists now with `/muzzlestats` that pulls a generic all-time report. Do we still care about time-based stats or should we just leave this as is?

**Comment by arrozconfrijoles** [comment]
I think it would be cool if we got a muzzle heat-map going but it could be tabled for now.

**Comment by sfreeman422** [comment]
Time based stats are added. If we build out a heatmap were gunna need an entire front end so I'm not gunna address that on this ticket.
