### ISSUE TITLE
User Reputation Database

### ISSUE THREAD

**Issue by arrozconfrijoles** [dev-chat/mocker#33]
Some users continually `/muzzle` individuals without an equal response from said individual. We can create a way to track this with a reputation score.

**Solution**
Every time a user muzzles someone their rep with that person falls by 1 point. Initially everyone's score will start at 0. 

**Example**
User A muzzles B 4 times.
User B muzzles A 3 times.

A's rep with B: -4
B's rep with A: -3

**Further Building**
How would we have rep increased? Would we have a system where User A can applaud B for some act and give his rep with him +1? In that case B's rep with A would be increased to -2.

How would this tie into the backfire feature? Would each negative rep be worth half a percent of backfire?

**Comment by CoMoFo** [comment]
[Delete this](https://media.giphy.com/media/xULW8N9O5WD32L5052/giphy.gif)

**Comment by sfreeman422** [comment]
Closing this because #39 exists.
