### ISSUE TITLE
@channel auto-muzzle

### ISSUE THREAD

**Issue by arrozconfrijoles** [dev-chat/mocker#6]
**Describe the Problem**
Users show no regard for other's time and will tag @channel in #gen. To prevent this egregious misuse of a push notification we need to institute some muzzled consequences.

**Describe the solution you'd like**
1. User tags @channel in #general
2. Timer begins counting down from 10 minutes
3. A counter will begin tracking how many "muzzle" emojis that initial @channel contains
4. When the number of muzzle emojis is greater than or equal to five the user will be muzzled for 5 minutes

**Comment by arrozconfrijoles** [comment]
Would also lead to people using @channel properly where they include a statement relevant to the reason that all 25 bros need to be notified

**Comment by arrozconfrijoles** [comment]
**Describe the Problem**
Users show no regard for other's time and will tag @channel in #gen. To prevent this egregious misuse of a push notification we need to institute some muzzled consequences.

**Describe the solution you'd like**
1. User tags @channel in #general
2. Timer begins counting down from 10 minutes
3. A counter will begin tracking how many "muzzle" emojis that initial @channel contains
4. When the number of muzzle emojis is greater than or equal to five the user will be muzzled for 5 minutes

**Comment by arrozconfrijoles** [comment]
I think this is somewhat of a different issue unrelated to the @channel tag. Could possibly remove this from this thread.
___________________________

**Problem**
First message while muzzled shouldn't result in the 5 minute penalty. User should first know that they're muzzled before being eligible for penalty

**Solution**
Second message onward that is muzzled will then have the @chan/here/alt-user penalty enforced

**Comment by sfreeman422** [comment]
@arrozconfrijoles Can you clean this up? There's like 5 ideas here lol. Delete the unnecessary ones and consolidate the idea into one post at the top.

**Comment by sfreeman422** [comment]
Closing this one, its unnecessary.
