### ISSUE TITLE
/clap functionality

### ISSUE THREAD

**Issue by sfreeman422** [dev-chat/mocker#7]
**Is your feature request related to a problem? Please describe.**
It 👏 would 👏 be 👏  nice 👏  to 👏  have 👏  a 👏 way 👏  to 👏  generate 👏  text 👏 like 👏 this 👏 

**Describe the solution you'd like**
Be able to send `/clap my message is here` to then have my message posted as `my 👏 message 👏  is 👏  here`

**Comment by sfreeman422** [comment]
Added to latest master

**Comment by arrozconfrijoles** [comment]
We need to add Trump hands though this might fall under the #57 
we could use the okay hand and the two palms facing outwards. Can't remember the third hand emoji

**Comment by arrozconfrijoles** [comment]
pointing up finger is the third emoji

**Comment by sfreeman422** [comment]
Closing, we are not adding trump hands.
